- hosts: sns_appliances
  tasks:
  - name: Get appliance information
    sns_command:
      appliance: "{{ hostvars[inventory_hostname].appliance }}"
      command: SYSTEM PROPERTY
    register: sysprop
  
  - name: Extract version
    sns_getconf:
      result: "{{ sysprop.result }}"
      section: Result
      token: Version
    register: version
  
  - name: Extract model
    sns_getconf:
      result: "{{ sysprop.result }}"
      section: Result
      token: Model
    register: model

  - name: Get appliance name
    sns_command:
      appliance: "{{ hostvars[inventory_hostname].appliance }}"
      command: SYSTEM IDENT
    register: ident

  - name: Extract system name
    sns_getconf:
      result: "{{ ident.result }}"
      section: Result
      token: SystemName
    register: sysname

  - debug:
      msg: "Appliance: {{ sysname.value }}, model: {{ model.value }}, firmware version: {{ version.value }}"
